//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string COMPANY { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string LOCATION { get; set; }
    }
}
