//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY()
        {
            this.locations = new HashSet<location>();
        }
    
        public int ID { get; set; }
        public string ORDER_NUM { get; set; }
        public string TRUCK { get; set; }
        public string DRIVER { get; set; }
        public Nullable<int> CLIENT { get; set; }
        public string FROM { get; set; }
        public string TO { get; set; }
        public System.DateTime DEPART_DAY { get; set; }
        public Nullable<System.DateTime> DELIVERY_DAY { get; set; }
        public string MATERIAL { get; set; }
        public int LOAD { get; set; }
        public string AUTHORITY { get; set; }
        public Nullable<System.DateTime> COMPLETED { get; set; }
        public Nullable<System.DateTime> ACCEPTED { get; set; }
        public Nullable<System.DateTime> STARTED { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual DRIVER DRIVER1 { get; set; }
        public virtual DRIVER DRIVER2 { get; set; }
        public virtual TRUCK TRUCK1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<location> locations { get; set; }
    }
}
