//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaitsoEntities : DbContext
    {
        public MaitsoEntities()
            : base("name=MaitsoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENTS { get; set; }
        public virtual DbSet<DELIVERY> DELIVERies { get; set; }
        public virtual DbSet<DRIVER> DRIVERS { get; set; }
        public virtual DbSet<TRUCK> TRUCKS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<location> locations { get; set; }
    }
}
