//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int delivery { get; set; }
        public string driver { get; set; }
        public string location1 { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual DELIVERY DELIVERY1 { get; set; }
        public virtual DRIVER DRIVER1 { get; set; }
    }
}
