//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.DELIVERies = new HashSet<DELIVERY>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string USER_TYPE { get; set; }
        public int SALT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY> DELIVERies { get; set; }
        public virtual DRIVER DRIVER { get; set; }
    }
}
